# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LED.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import sys



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(480, 320)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../0_PROGRAMACION/RASBERRY_BUTTONS/awus036neh-llave-de-wifi-usb-alfa-network-320-mw-y-5-dbi-antena.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 161, 131))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 81 11pt \"Open Sans ExtraBold\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../0_PROGRAMACION/RASBERRY_BUTTONS/wifiap2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(100, 90))
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(False)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(160, 0, 321, 131))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '480.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(480, 320)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../0_PROGRAMACION/RASBERRY_BUTTONS/awus036neh-llave-de-wifi-usb-alfa-network-320-mw-y-5-dbi-antena.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 161, 131))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background-color: rgb(0, 255, 0);\n"
#"font: 81 11pt \"Open Sans ExtraBold\";")
#        icon1 = QtGui.QIcon()
#        icon1.addPixmap(QtGui.QPixmap("../0_PROGRAMACION/RASBERRY_BUTTONS/wifiap2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
#        self.pushButton.setIcon(icon1)
#        self.pushButton.setIconSize(QtCore.QSize(100, 90))
#        self.pushButton.setCheckable(True)
#        self.pushButton.setChecked(False)
#        self.pushButton.setAutoDefault(False)
#        self.pushButton.setDefault(False)
#        self.pushButton.setFlat(False)
#        self.pushButton.setObjectName("pushButton")
#        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
#        self.pushButton_6.setGeometry(QtCore.QRect(160, 0, 321, 131))
#        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
#        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
#        self.pushButton_11.setAutoFillBackground(False)
#        self.pushButton_11.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 81 11pt \"Open Sans ExtraBold\";")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../0_PROGRAMACION/RASBERRY_BUTTONS/ssh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon4)
        self.pushButton_11.setIconSize(QtCore.QSize(60, 70))
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setChecked(False)
        self.pushButton_11.setFlat(False)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(0, 210, 241, 101))
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.pushButton_12.setAutoFillBackground(False)
        self.pushButton_12.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 81 11pt \"Open Sans ExtraBold\";")
        self.pushButton_12.setIcon(icon)
        self.pushButton_12.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_12.setCheckable(True)
        self.pushButton_12.setChecked(False)
        self.pushButton_12.setFlat(False)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(240, 210, 241, 101))
        self.pushButton_13.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.pushButton_13.setAutoFillBackground(False)
        self.pushButton_13.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 81 11pt \"Open Sans ExtraBold\";")
        self.pushButton_13.setIcon(icon)
        self.pushButton_13.setIconSize(QtCore.QSize(90, 70))
        self.pushButton_13.setCheckable(True)
        self.pushButton_13.setChecked(False)
        self.pushButton_13.setFlat(False)
        self.pushButton_13.setObjectName("pushButton_13")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WIFI-HACK "))
        self.pushButton.setText(_translate("MainWindow", "THANOS"))
        self.pushButton_6.setText(_translate("MainWindow", "ROUTING"))
        self.pushButton_8.setText(_translate("MainWindow", "CONNECT &WIFI 1"))
        self.pushButton_10.setText(_translate("MainWindow", "CONNECT W&IFI 2"))
        self.pushButton_11.setText(_translate("MainWindow", "  S&ERVER SSH"))
        self.pushButton_12.setText(_translate("MainWindow", "MAC-1"))
        self.pushButton_13.setText(_translate("MainWindow", "MAC-2"))




# Eventos de botones 
    def Play_button_11_clicked(self):
        os.system("xterm -e 'bash -c \"sudo sh /etc/init.d/ssh start; exec bash\"'")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
